import { createRouter, createWebHashHistory } from 'vue-router'
// Generated by vue-router's file-based routing (`vue-router/vite`) from src/pages; typed in src/typed-router.d.ts.
import { routes } from 'vue-router/auto-routes'

declare module 'vue-router' {
  interface RouteMeta {
    /** Window title for the page, set from `definePage({ meta: { title } })`. */
    title?: string
  }
}

// Hash history: a packaged Tauri app serves static files from a custom protocol, so deep links must not hit the "server".
export const router = createRouter({ history: createWebHashHistory(), routes })

router.afterEach((to) => {
  document.title = to.meta.title ? `${to.meta.title} - __APP_TITLE__` : '__APP_TITLE__'
})
