// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthCode = `-- name: ConsumeAuthCode :one
UPDATE auth_codes SET used_at = $1
WHERE code_hash = $2 AND used_at IS NULL AND expires_at > $1
RETURNING user_id, code_challenge
`

type ConsumeAuthCodeParams struct {
	Now      *time.Time
	CodeHash []byte
}

type ConsumeAuthCodeRow struct {
	UserID        uuid.UUID
	CodeChallenge string
}

func (q *Queries) ConsumeAuthCode(ctx context.Context, arg ConsumeAuthCodeParams) (ConsumeAuthCodeRow, error) {
	row := q.db.QueryRow(ctx, consumeAuthCode, arg.Now, arg.CodeHash)
	var i ConsumeAuthCodeRow
	err := row.Scan(&i.UserID, &i.CodeChallenge)
	return i, err
}

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE magic_links SET used_at = $1
WHERE token_hash = $2 AND used_at IS NULL AND expires_at > $1
RETURNING email, client
`

type ConsumeMagicLinkParams struct {
	Now       *time.Time
	TokenHash []byte
}

type ConsumeMagicLinkRow struct {
	Email  string
	Client string
}

func (q *Queries) ConsumeMagicLink(ctx context.Context, arg ConsumeMagicLinkParams) (ConsumeMagicLinkRow, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, arg.Now, arg.TokenHash)
	var i ConsumeMagicLinkRow
	err := row.Scan(&i.Email, &i.Client)
	return i, err
}

const consumeOIDCState = `-- name: ConsumeOIDCState :one
DELETE FROM oidc_states WHERE state_hash = $1 AND expires_at > $2
RETURNING provider, code_verifier, nonce, client, redirect, client_challenge
`

type ConsumeOIDCStateParams struct {
	StateHash []byte
	Now       time.Time
}

type ConsumeOIDCStateRow struct {
	Provider        string
	CodeVerifier    string
	Nonce           string
	Client          string
	Redirect        string
	ClientChallenge string
}

func (q *Queries) ConsumeOIDCState(ctx context.Context, arg ConsumeOIDCStateParams) (ConsumeOIDCStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOIDCState, arg.StateHash, arg.Now)
	var i ConsumeOIDCStateRow
	err := row.Scan(
		&i.Provider,
		&i.CodeVerifier,
		&i.Nonce,
		&i.Client,
		&i.Redirect,
		&i.ClientChallenge,
	)
	return i, err
}

const createAuthCode = `-- name: CreateAuthCode :exec
INSERT INTO auth_codes (code_hash, user_id, code_challenge, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateAuthCodeParams struct {
	CodeHash      []byte
	UserID        uuid.UUID
	CodeChallenge string
	ExpiresAt     time.Time
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthCode,
		arg.CodeHash,
		arg.UserID,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO identities (provider, subject, user_id) VALUES ($1, $2, $3)
`

type CreateIdentityParams struct {
	Provider string
	Subject  string
	UserID   uuid.UUID
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity, arg.Provider, arg.Subject, arg.UserID)
	return err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (token_hash, email, client, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateMagicLinkParams struct {
	TokenHash []byte
	Email     string
	Client    string
	ExpiresAt time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.Exec(ctx, createMagicLink,
		arg.TokenHash,
		arg.Email,
		arg.Client,
		arg.ExpiresAt,
	)
	return err
}

const createOIDCState = `-- name: CreateOIDCState :exec
INSERT INTO oidc_states (state_hash, provider, code_verifier, nonce, client, redirect, client_challenge, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOIDCStateParams struct {
	StateHash       []byte
	Provider        string
	CodeVerifier    string
	Nonce           string
	Client          string
	Redirect        string
	ClientChallenge string
	ExpiresAt       time.Time
}

func (q *Queries) CreateOIDCState(ctx context.Context, arg CreateOIDCStateParams) error {
	_, err := q.db.Exec(ctx, createOIDCState,
		arg.StateHash,
		arg.Provider,
		arg.CodeVerifier,
		arg.Nonce,
		arg.Client,
		arg.Redirect,
		arg.ClientChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, kind, token_hash, refresh_hash, expires_at, refresh_expires_at, created_at, last_used_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8, $9, $10)
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Kind             string
	TokenHash        []byte
	RefreshHash      []byte
	ExpiresAt        time.Time
	RefreshExpiresAt *time.Time
	CreatedAt        time.Time
	UserAgent        string
	Ip               string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.RefreshHash,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.CreatedAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash, email_verified_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, email_verified_at, created_at
`

type CreateUserParams struct {
	Email           string
	Name            string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
}

// Auth persistence. Secrets are only ever passed in as SHA-256 hashes.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthCodes = `-- name: DeleteExpiredAuthCodes :execrows
DELETE FROM auth_codes WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAuthCodes(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthCodes, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredMagicLinks = `-- name: DeleteExpiredMagicLinks :execrows
DELETE FROM magic_links WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredMagicLinks(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMagicLinks, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOIDCStates = `-- name: DeleteExpiredOIDCStates :execrows
DELETE FROM oidc_states WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredOIDCStates(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCStates, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE (kind = 'web' AND expires_at < $1)
   OR (kind = 'native' AND refresh_expires_at < $1)
   OR revoked_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityUserID = `-- name: GetIdentityUserID :one
SELECT user_id FROM identities WHERE provider = $1 AND subject = $2
`

type GetIdentityUserIDParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetIdentityUserID(ctx context.Context, arg GetIdentityUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIdentityUserID, arg.Provider, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, kind, token_hash, refresh_hash, expires_at, refresh_expires_at, created_at, last_used_at, revoked_at, user_agent, ip FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, kind, token_hash, refresh_hash, expires_at, refresh_expires_at, created_at, last_used_at, revoked_at, user_agent, ip FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, email_verified_at, created_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, email_verified_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users SET email_verified_at = $1 WHERE id = $2 AND email_verified_at IS NULL
`

type MarkUserEmailVerifiedParams struct {
	VerifiedAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, arg.VerifiedAt, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = $1 WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	RevokedAt *time.Time
	UserID    uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.RevokedAt, arg.UserID)
	return err
}

const rotateSession = `-- name: RotateSession :execrows
UPDATE sessions
SET token_hash = $1, refresh_hash = $2, expires_at = $3,
    refresh_expires_at = $4, last_used_at = $5, user_agent = $6, ip = $7
WHERE id = $8 AND refresh_hash = $9 AND revoked_at IS NULL AND refresh_expires_at > $5
`

type RotateSessionParams struct {
	NewTokenHash     []byte
	NewRefreshHash   []byte
	ExpiresAt        time.Time
	RefreshExpiresAt *time.Time
	Now              time.Time
	UserAgent        string
	Ip               string
	ID               uuid.UUID
	OldRefreshHash   []byte
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession,
		arg.NewTokenHash,
		arg.NewRefreshHash,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.Now,
		arg.UserAgent,
		arg.Ip,
		arg.ID,
		arg.OldRefreshHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type SetUserPasswordHashParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = $1, expires_at = $2
WHERE id = $3 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	LastUsedAt time.Time
	ExpiresAt  time.Time
	ID         uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastUsedAt, arg.ExpiresAt, arg.ID)
	return err
}
