// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one

INSERT INTO notes (owner_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, body, created_at
`

type CreateNoteParams struct {
	OwnerID uuid.UUID
	Title   string
	Body    string
}

// Every notes query is scoped by owner_id: never add one that is not.
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.OwnerID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesAfter = `-- name: ListNotesAfter :many
SELECT id, owner_id, title, body, created_at
FROM notes
WHERE owner_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotesAfterParams struct {
	OwnerID        uuid.UUID
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

func (q *Queries) ListNotesAfter(ctx context.Context, arg ListNotesAfterParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesAfter,
		arg.OwnerID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesFirstPage = `-- name: ListNotesFirstPage :many
SELECT id, owner_id, title, body, created_at
FROM notes
WHERE owner_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListNotesFirstPageParams struct {
	OwnerID   uuid.UUID
	PageLimit int32
}

func (q *Queries) ListNotesFirstPage(ctx context.Context, arg ListNotesFirstPageParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesFirstPage, arg.OwnerID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
