// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, body)
VALUES ($1, $2)
RETURNING id, title, body, created_at
`

type CreateNoteParams struct {
	Title string
	Body  string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesAfter = `-- name: ListNotesAfter :many
SELECT id, title, body, created_at
FROM notes
WHERE (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotesAfterParams struct {
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

func (q *Queries) ListNotesAfter(ctx context.Context, arg ListNotesAfterParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesFirstPage = `-- name: ListNotesFirstPage :many
SELECT id, title, body, created_at
FROM notes
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListNotesFirstPage(ctx context.Context, pageLimit int32) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesFirstPage, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
