#!/usr/bin/env node
// Generates agents/*.md from agents-src/*.md + the model-routing table below.
// One source per role, one file per tier, so tier variants never drift. Run after editing agents-src/.
//
// Routing policy (by task complexity = the change's risk tier):
//   complex (tier L) → opus   / medium effort
//   normal  (tier M) → sonnet / high effort
//   simple  (tier S) → sonnet / low effort
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TIERS, ROLES } from './lib.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'agents-src');
const out = path.join(root, 'agents');
fs.mkdirSync(out, { recursive: true });
for (const f of fs.readdirSync(out)) if (f.endsWith('.md')) fs.rmSync(path.join(out, f), { maxRetries: 5, retryDelay: 100 });

for (const [role, tiers] of Object.entries(ROLES)) {
  const text = fs.readFileSync(path.join(src, `${role}.md`), 'utf8');
  for (const t of tiers) {
    const { model, effort, suffix, label } = TIERS[t];
    const name = role + suffix;
    const body = text
      .replace(/^name: .*$/m, `name: ${name}`)
      .replace(/^description: (.*)$/m, (_, d) => `description: ${tiers.length > 1 ? `[${label} — ${model}/${effort}] ` : ''}${d}`)
      .replace(/^tools: /m, `model: ${model}\neffort: ${effort}\ntools: `)
      .replace(/^(---\r?\n[\s\S]*?\r?\n---\r?\n)/, `$1<!-- GENERATED by scripts/build-agents.mjs from agents-src/${role}.md — edit the source -->\n`);
    fs.writeFileSync(path.join(out, `${name}.md`), body);
    console.log(`agents/${name}.md  ${model}/${effort}`);
  }
}
